name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: get dependency libs
      run: make git-submodule

    - name: build
      run: make

    - name: run
      run: ./bin/main

